Java = {}

[Display]

	[Display.General]
		# 
		# The name of your modpack.
		# If blank, the modpack name will be auto-detected from supported launchers.
		# This auto-detection isn't perfect, so you can override it here if needed.
		modpackName = ""

	[Display.WindowTitle]
		# 
		# Enable this if you want to change the name of the Minecraft window.
		enableCustomWindowTitle = true
		# 
		# The name you want your Minecraft window to be. Put "%mc" to include the original
		# window title's contents to help identify the Minecraft version for example.
		# 
		# Warning: Mojang have asked people to not change their branding entirely and made it
		# harder for modders to change it at all as of MC 1.15 and newer. They clearly don't like
		# people taking full credit for their work and I understand that.
		# Please make sure you keep the "%mc" in your customWindowTitleText as a sign of respect.
		# Keeping it also helps others troubleshoot your pack by knowing what Minecraft version
		# it's based on - especially useful if your modpack has multiple major releases that
		# span across different Minecraft versions.
		# 
		# Note: Put "%modpackName" to fill in your modpack's display name from [Display.General] modpackName.
		# 
		# Examples:
		# - "%modpackName - %mc" = "ModpackName - Minecraft* 1.19.3"
		# - "%mc - %modpackName" = "Minecraft* 1.19.3 - ModpackName"
		# - "%modpackName (%mc)" = "ModpackName (Minecraft* 1.19.3)"
		# - "%modpackName (%mc)" = "ModpackName (Minecraft* 1.19.3)"
		# - "ModpackName v2 based on %mc" = "ModpackName v2 based on Minecraft* 1.19.3"
		# 
		# Note: enableCustomWindowTitle must be enabled for this to take effect.
		customWindowTitleText = "%modpackName - %mc"

	[Display.Icon]
		# 
		# Enable this if you want itlt to use its HiDPI-aware (aka Retina support) icon setting
		# feature with the Vanilla game icon, obtained directly from the game's resources.
		# 
		# Turning this on should give you a more crisp and detailed icon on higher resolution displays,
		# rather than the comparatively blurry 32px PNG that is normally used.
		enableEnhancedVanillaIcon = true
		# 
		# Enable this if you want to change the window and taskbar icon of the Minecraft window.
		# ICO, ICNS and PNG icons provided to this mod are supported on all operating systems.
		# 
		# Note: The icon needs to be placed in config/itlt/icon.(ico/icns/png).
		# 
		# Note: See the itlt wiki for more info.
		# 
		# Note: This will override the enableEnhancedVanillaIcon when a valid custom icon is found.
		enableCustomIcon = true
		# 
		# Enable this if you want itlt to automatically detect your modpack's icon when launching
		# from a supported launcher. If unable to auto-detect, it will fallback to a provided
		# icon.ico/icon.icns/icon.png file if available.
		# 
		# Note: enableCustomIcon must be enabled for this to take effect.
		enableUsingAutodetectedIcon = true

	[Display.WelcomeScreen]
		# 
		# Enable this if you want to show a welcome screen to your users the first time they
		# start your modpack. You can customise the text shown using a text file.
		# 
		# Note: The text file needs to be placed in config/itlt/welcome.txt
		# 
		# Warning: This feature is experimental and may change in future v2.x releases. Check the
		# changelog before updating if you use this. The changelog will make any breaking changes
		# to this feature clear. If there's no mention of this feature in the changelog, rest assured
		# you can update without needing to make any changes to your welcome.txt.
		enableWelcomeScreen = false
		# 
		# The welcome screen header shows "Welcome to x". This setting lets you change x.
		# 
		# - If blank (default), itlt will use your modpack's name from [Display.General] modpackName.
		# - Otherwise x will be whatever you put here.
		customWelcomeHeaderModpackDisplayName = ""

[ServerList]
	# 
	# Enable this to have itlt add default servers to the Multiplayer list from a JSON file.
	# 
	# Note: The JSON needs to be placed in config/itlt/servers.json
	# 
	# Warning: This feature is experimental and may change in future v2.x releases. Check the
	# changelog before updating if you use this. The changelog will make any breaking changes
	# to this feature clear. If there's no mention of this feature in the changelog, rest assured
	# you can update without needing to make any changes to your servers.json.
	enableCustomServerListEntries = false

[Internal]
	# 
	# The version of itlt that created this config file. Intended to be used for migrating
	# config changes when you update the mod. Please don't touch this, this is for itlt itself to change.
	configVersion = "2.2.1"

